In [1]:
import numpy as np

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.identity(3, dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [10]:
np.zeros((3,4))+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [22]:
np.empty((3,4,2))

array([[[6.79038653e-313, 6.79038653e-313],
        [2.14321575e-312, 2.48273508e-312],
        [2.33419537e-312, 2.31297541e-312],
        [2.46151512e-312, 2.22809558e-312]],

       [[8.48798317e-313, 2.05833592e-312],
        [2.05833592e-312, 6.79038653e-313],
        [2.46151512e-312, 2.37663529e-312],
        [1.29441743e-312, 2.46151512e-312]],

       [[2.37663529e-312, 9.33678149e-313],
        [2.10077583e-312, 2.37663529e-312],
        [1.29441743e-312, 2.05833592e-312],
        [2.44029516e-312, 8.70018275e-313]]])

In [23]:
np.linspace(2,6)

array([2.        , 2.08163265, 2.16326531, 2.24489796, 2.32653061,
       2.40816327, 2.48979592, 2.57142857, 2.65306122, 2.73469388,
       2.81632653, 2.89795918, 2.97959184, 3.06122449, 3.14285714,
       3.2244898 , 3.30612245, 3.3877551 , 3.46938776, 3.55102041,
       3.63265306, 3.71428571, 3.79591837, 3.87755102, 3.95918367,
       4.04081633, 4.12244898, 4.20408163, 4.28571429, 4.36734694,
       4.44897959, 4.53061224, 4.6122449 , 4.69387755, 4.7755102 ,
       4.85714286, 4.93877551, 5.02040816, 5.10204082, 5.18367347,
       5.26530612, 5.34693878, 5.42857143, 5.51020408, 5.59183673,
       5.67346939, 5.75510204, 5.83673469, 5.91836735, 6.        ])

In [24]:
np.linspace(2,6, 10)

array([2.        , 2.44444444, 2.88888889, 3.33333333, 3.77777778,
       4.22222222, 4.66666667, 5.11111111, 5.55555556, 6.        ])

In [25]:
np.logspace(2,4,10, base = 10)

array([  100.        ,   166.81005372,   278.25594022,   464.15888336,
         774.26368268,  1291.54966501,  2154.43469003,  3593.8136638 ,
        5994.84250319, 10000.        ])

In [26]:
a = np.arange(4,20).reshape(4,4)

In [27]:
a

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [29]:
a.max(axis = 1)

array([ 7, 11, 15, 19])

In [30]:
a.max(axis = 0)

array([16, 17, 18, 19])

In [120]:
b = np.array([1000,2,3,4])

In [121]:
b

array([1000,    2,    3,    4])

In [33]:
#transpose of b is same as b doesn't have second degree of freedom
b.T

array([1, 2, 3, 4])

In [122]:
x = b

In [123]:
id(x)

2829728442960

In [124]:
id(b)

2829728442960

In [125]:
id(x[0])

2829731209808

In [128]:
id(b[0])

2829731184464

In [127]:
id(x[0]) == id(b[0])

True

In [41]:
id(x[1]) == id(b[0])

True

In [109]:
b1 = np.array([10,2,3,4])

In [110]:
x = b1

In [111]:
x


array([10,  2,  3,  4])

In [112]:
id(x[0])

2829731209264

In [113]:
id(b1[0])

2829731181648

In [114]:
a = 10

In [117]:
id(a)

2829608512080

In [119]:
id(x[0]) == id(b1[0])

True

In [100]:
print(id(x[0]))

2829731184240


In [101]:
print(id(b1[0]))

2829731182512


In [99]:
id(x)

2829728443632

In [74]:
id(b1)

2829728443632

In [86]:
id(x[0])  == id(b1[0])

True

In [87]:
type(x[0])

numpy.int32

In [88]:
type(b1[0])

numpy.int32

In [89]:
type(b1)

numpy.ndarray

In [103]:
a = np.arange(27)

In [108]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [104]:
b = a[1:5]

In [105]:
a[0]

0

In [107]:
b[1]

2

In [129]:
u, v = id(x[0]), id(b1[0])

In [132]:
u

2829731209584

In [133]:
v

2829731209584