In [1]:
t = ("Abishek", 1, 2.9, 4+7j, True)


In [2]:
t

('Abishek', 1, 2.9, (4+7j), True)

In [3]:
type(t)

tuple

In [4]:
t[0:2]

('Abishek', 1)

In [5]:
t[::-1]

(True, (4+7j), 2.9, 1, 'Abishek')

In [6]:
l = ["kumar", 325, 4+7j]

In [7]:
l[0] = "Abh"

In [8]:
l


['Abh', 325, (4+7j)]

In [9]:
t[0]="xyz"

TypeError: 'tuple' object does not support item assignment

In [19]:
s= "AbAi"

In [20]:
s[0].replace('A','a')


'a'

In [14]:
t1 = (3,5,6)

In [15]:
t2 = t+t1

In [16]:
t2

('Abishek', 1, 2.9, (4+7j), True, 3, 5, 6)

In [21]:
s[0]

'A'

In [26]:
l[0]= "Abhi"

In [27]:
l

['Abhi', 325, (4+7j)]

In [28]:
t1


(3, 5, 6)

In [29]:
t1 = ([1,2,3.4], "Abhi", True)

In [32]:
t1[0][0] = 4

In [33]:
t1

([4, 2, 3.4], 'Abhi', True)

In [34]:
l2 = list(t1)

In [35]:
l2

[[4, 2, 3.4], 'Abhi', True]

In [36]:
t1

([4, 2, 3.4], 'Abhi', True)

In [37]:
l = [1,2,2,2,3,3,3,4,4,5,5,3.4,3.46,7,8,9]

In [38]:
set(l)

{1, 2, 3, 3.4, 3.46, 4, 5, 7, 8, 9}

In [39]:
s1 = {2,3,4}

In [40]:
s1[0:1]

TypeError: 'set' object is not subscriptable

In [41]:
s1[0]

TypeError: 'set' object is not subscriptable

In [42]:
s1.add("Abhi")

In [43]:
s1


{2, 3, 4, 'Abhi'}

In [44]:
s1.add("Abhi")

In [45]:
s1

{2, 3, 4, 'Abhi'}

In [46]:
s1.add([2,4,6,7])

TypeError: unhashable type: 'list'

In [49]:
s1.remove(45)

KeyError: 45

In [48]:
s1

{2, 3, 'Abhi'}

In [50]:
s1.discard(45)

In [51]:
s1[0] = 6

TypeError: 'set' object does not support item assignment

In [52]:
d = {4:"Abhi"}

In [53]:
d


{4: 'Abhi'}

In [54]:
d[4]

'Abhi'

In [59]:
d = {"key1": 2, "key2" : "Abhi", 435: [3,2,4,5]}

In [60]:
d["key1"]

2

In [61]:
d[435][0]

3

In [64]:
d1 = {"key1": 2, "key1" : "Abhi", 435: [3,2,4,5]}

In [66]:
d1["key1"]

'Abhi'

In [67]:
d1

{'key1': 'Abhi', 435: [3, 2, 4, 5]}

In [71]:
d1["key2"] = "Hi"

In [72]:
d1

{'key1': 'Hi', 435: [3, 2, 4, 5], 'key2': 'Hi'}

In [77]:
type(d1.keys())

dict_keys

In [74]:
d1.values()

dict_values(['Hi', [3, 2, 4, 5], 'Hi'])

In [76]:
list(d1)

['key1', 435, 'key2']

In [79]:
d1["key3"] = 3421

In [80]:
d1

{'key1': 'Hi', 435: [3, 2, 4, 5], 'key2': 'Hi', 'key3': 3421}

In [81]:
del d["key1"]

In [82]:
d

{'key2': 'Abhi', 435: [3, 2, 4, 5]}

In [85]:
d[(1,2,3)] = 345

In [86]:
d.get("key2")

'Abhi'

In [87]:
d1 ={"ID": 3}

In [88]:
d+d1

TypeError: unsupported operand type(s) for +: 'dict' and 'dict'

In [89]:
d.update(d1)

In [90]:
d

{'key2': 'Abhi', 435: [3, 2, 4, 5], (1, 2, 3): 345, 'ID': 3}

In [94]:
t1 = ("Abhi", 2, True)

In [95]:
t1.index(True)

2

In [96]:
l = [1,2,3]

In [97]:
l.append(l)

In [98]:
l

[1, 2, 3, [...]]

In [99]:
l[3]

[1, 2, 3, [...]]

In [100]:
l[0]

1

In [101]:
l.append(5)

In [102]:
l

[1, 2, 3, [...], 5]

In [103]:
{(3,4,5),4,5}

{(3, 4, 5), 4, 5}

In [104]:
t = (1,2,3)

In [105]:
t[0]

1

In [110]:
set = {1,2,3}

In [109]:
set[0]

TypeError: 'set' object is not subscriptable

In [116]:
s ='doesn\nt'

In [117]:
s

'doesn\nt'

In [118]:
print(s)

doesn
t


In [129]:
list = [[1,2,3],[1,2,3]]

In [130]:
for x in list:
 print(x)

[1, 2, 3]
[1, 2, 3]


In [122]:
list

[1, 2, 3]

In [134]:
import numpy as np
a = np.array([1,2,3])
a

array([1, 2, 3])

In [135]:
a[0]

1

In [136]:
type(list)

list

In [137]:
class()

SyntaxError: invalid syntax (Temp/ipykernel_14116/3499591618.py, line 1)

In [139]:
a = np.array([[1,2,3],[1,2,3]])
a

array([[1, 2, 3],
       [1, 2, 3]])

In [140]:
a[0:1,1:3]

array([[2, 3]])

In [141]:
l = [1,3,5]

In [143]:
l+[2]

[1, 3, 5, 2]