In [1]:
import pandas as pd


In [6]:
df = pd.DataFrame({
    'col1': [1,2,3,4,5],
    'col2': [45,56,67,34,34],
    'col3':"Abhishek Kumar Bablu Jack Nick".split()
})

In [7]:
df

col1  col2      col3
0     1    45  Abhishek
1     2    56     Kumar
2     3    67     Bablu
3     4    34      Jack
4     5    34      Nick

In [8]:
df["col4"] = df.col1 * df.col1

In [9]:
df

col1  col2      col3  col4
0     1    45  Abhishek     1
1     2    56     Kumar     4
2     3    67     Bablu     9
3     4    34      Jack    16
4     5    34      Nick    25

In [12]:
df["col5"] = df.col3.str[0]

In [13]:
df

col1  col2      col3  col4 col5
0     1    45  Abhishek     1    A
1     2    56     Kumar     4    K
2     3    67     Bablu     9    B
3     4    34      Jack    16    J
4     5    34      Nick    25    N

In [14]:
def test(a):
    return a**2

In [15]:
df["col4_4"] = df["col1"].apply(test)

In [16]:
df

col1  col2      col3  col4 col5  col4_4
0     1    45  Abhishek     1    A       1
1     2    56     Kumar     4    K       4
2     3    67     Bablu     9    B       9
3     4    34      Jack    16    J      16
4     5    34      Nick    25    N      25

In [17]:
df["col6_6"] = df["col5"].apply(lambda a : 's' if a == 's' else 'z')

In [18]:
df

col1  col2      col3  col4 col5  col4_4 col6_6
0     1    45  Abhishek     1    A       1      z
1     2    56     Kumar     4    K       4      z
2     3    67     Bablu     9    B       9      z
3     4    34      Jack    16    J      16      z
4     5    34      Nick    25    N      25      z

In [19]:
df['col7'] = df['col3'].apply(len)

In [20]:
df

col1  col2      col3  col4 col5  col4_4 col6_6  col7
0     1    45  Abhishek     1    A       1      z     8
1     2    56     Kumar     4    K       4      z     5
2     3    67     Bablu     9    B       9      z     5
3     4    34      Jack    16    J      16      z     4
4     5    34      Nick    25    N      25      z     4

In [22]:
import math

In [24]:
df['col8'] = df['col2'].apply(math.log)

In [25]:
df

col1  col2      col3  col4 col5  col4_4 col6_6  col7      col8
0     1    45  Abhishek     1    A       1      z     8  3.806662
1     2    56     Kumar     4    K       4      z     5  4.025352
2     3    67     Bablu     9    B       9      z     5  4.204693
3     4    34      Jack    16    J      16      z     4  3.526361
4     5    34      Nick    25    N      25      z     4  3.526361

In [26]:
df["col_9"] = [i**2 for i in df.col8]

In [27]:
df

col1  col2      col3  col4 col5  col4_4 col6_6  col7      col8      col_9
0     1    45  Abhishek     1    A       1      z     8  3.806662  14.490679
1     2    56     Kumar     4    K       4      z     5  4.025352  16.203456
2     3    67     Bablu     9    B       9      z     5  4.204693  17.679440
3     4    34      Jack    16    J      16      z     4  3.526361  12.435219
4     5    34      Nick    25    N      25      z     4  3.526361  12.435219

In [29]:
df["col_10"] = list(map(lambda a : a**2, df.col8))

In [30]:
df

col1  col2      col3  col4 col5  col4_4 col6_6  col7      col8      col_9  \
0     1    45  Abhishek     1    A       1      z     8  3.806662  14.490679   
1     2    56     Kumar     4    K       4      z     5  4.025352  16.203456   
2     3    67     Bablu     9    B       9      z     5  4.204693  17.679440   
3     4    34      Jack    16    J      16      z     4  3.526361  12.435219   
4     5    34      Nick    25    N      25      z     4  3.526361  12.435219   

      col_10  
0  14.490679  
1  16.203456  
2  17.679440  
3  12.435219  
4  12.435219

In [31]:
import numpy as np

In [32]:
l = ["Abhi", 1,2,3,4]

In [34]:
type(np.array(l))

numpy.ndarray

In [36]:
np.array([3,4,5,6,3.0])

array([3., 4., 5., 6., 3.])

In [39]:
a = np.array([[1,2], [3,4]])

In [40]:
a

array([[1, 2],
       [3, 4]])

In [41]:
a[1][1]

4

In [44]:
a = np.array([1,2,3,4], ndmin = 4)

In [48]:
a[0][0][0][0]

1

In [49]:
np.asanyarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [50]:
np.mat([1,2,3,4])

matrix([[1, 2, 3, 4]])

In [51]:
np.asanyarray(np.mat(a))

matrix([[1, 2, 3, 4]])

In [52]:
np.asanyarray(a)

array([[[[1, 2, 3, 4]]]])

In [53]:
np.fromfunction(lambda i, j : i ==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [59]:
(np.fromfunction(lambda i, j, z : i*j*z, (3,3,2), dtype = int))

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]]])

In [60]:
np.fromfunction(lambda i, j, z, p : i*j*z*p, (4,3,3,2), dtype = int)

array([[[[ 0,  0],
         [ 0,  0],
         [ 0,  0]],

        [[ 0,  0],
         [ 0,  0],
         [ 0,  0]],

        [[ 0,  0],
         [ 0,  0],
         [ 0,  0]]],


       [[[ 0,  0],
         [ 0,  0],
         [ 0,  0]],

        [[ 0,  0],
         [ 0,  1],
         [ 0,  2]],

        [[ 0,  0],
         [ 0,  2],
         [ 0,  4]]],


       [[[ 0,  0],
         [ 0,  0],
         [ 0,  0]],

        [[ 0,  0],
         [ 0,  2],
         [ 0,  4]],

        [[ 0,  0],
         [ 0,  4],
         [ 0,  8]]],


       [[[ 0,  0],
         [ 0,  0],
         [ 0,  0]],

        [[ 0,  0],
         [ 0,  3],
         [ 0,  6]],

        [[ 0,  0],
         [ 0,  6],
         [ 0, 12]]]])

In [76]:
a = np.fromfunction(lambda i, j, z : i*j*z, (4,3,2), dtype = int)

In [77]:
a.reshape(3,8)

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 2, 0, 0, 0, 2],
       [0, 4, 0, 0, 0, 3, 0, 6]])

In [82]:
a.reshape(3,-1)

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 2, 0, 0, 0, 2],
       [0, 4, 0, 0, 0, 3, 0, 6]])

In [64]:
a.ndim

3

In [65]:
a.size

24

In [66]:
a.shape

(4, 3, 2)

In [67]:
a.dtype


dtype('int32')

In [69]:
a = np.fromfunction(lambda i, j : i*j, (4,3), dtype = int)

In [70]:
pd.DataFrame(a)

0  1  2
0  0  0  0
1  0  1  2
2  0  2  4
3  0  3  6

In [71]:
np.random.rand(100, 4)

array([[0.29044664, 0.6465325 , 0.59746002, 0.42808992],
       [0.74351191, 0.83847512, 0.42554465, 0.27509966],
       [0.73412914, 0.62100592, 0.89116919, 0.62981587],
       [0.35600036, 0.09923121, 0.2235596 , 0.39003112],
       [0.37523878, 0.46859895, 0.21260613, 0.49525332],
       [0.44950145, 0.40161701, 0.88966637, 0.78549061],
       [0.39432126, 0.56248731, 0.91613726, 0.34242886],
       [0.10717064, 0.50442337, 0.05753632, 0.17891349],
       [0.25498846, 0.83266539, 0.27844321, 0.63750088],
       [0.85527415, 0.55488266, 0.68054161, 0.82370275],
       [0.93136814, 0.55599215, 0.95120693, 0.58062121],
       [0.34747083, 0.51806418, 0.38574016, 0.64088189],
       [0.64915165, 0.75873777, 0.09740154, 0.64538815],
       [0.75429615, 0.32978093, 0.97772025, 0.5894759 ],
       [0.45629183, 0.71404687, 0.55886962, 0.26705881],
       [0.83554623, 0.22034689, 0.05236685, 0.83880171],
       [0.52905797, 0.08784294, 0.09012902, 0.23447412],
       [0.92024218, 0.06521705,

In [73]:
np.random.randint(4,50)

26

In [74]:
np.random.randn(4,5)

array([[-0.12062521, -0.73930471,  1.47230303, -0.20177108,  1.34977866],
       [ 1.1984009 , -0.27337058,  1.08665872,  0.86335124,  0.34936973],
       [ 0.10119261, -0.42562812, -0.11003527, -0.07165053,  0.7171724 ],
       [ 0.31390027,  0.40741077,  0.11353099,  1.10784389,  0.02587471]])

In [75]:
pd.DataFrame(np.random.randn(4,5))

0         1         2         3         4
0 -0.950458  0.329538 -0.003609 -0.277984 -0.411856
1 -0.750503  0.665443 -0.637305  0.142859 -0.271625
2  1.421488  0.955253  0.681413  1.932530  0.149864
3  1.344453 -0.571256  0.429407 -0.287517  0.484030

In [84]:
a1 = np.arange(4,10,.2)

In [85]:
a1

array([4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4,
       6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. ,
       9.2, 9.4, 9.6, 9.8])

In [86]:
a1[1:4]

array([4.2, 4.4, 4.6])

In [88]:
arr = np.random.rand(4, 5)

In [90]:
arr

array([[0.34011707, 0.76321887, 0.46959978, 0.96842855, 0.94926278],
       [0.00578079, 0.11008426, 0.97456154, 0.25350418, 0.37955959],
       [0.47534932, 0.93694308, 0.25583818, 0.58251287, 0.6674287 ],
       [0.84622084, 0.07690218, 0.84918105, 0.92705247, 0.70841282]])

In [91]:
arr> .5

array([[False,  True, False,  True,  True],
       [False, False,  True, False, False],
       [False,  True, False,  True,  True],
       [ True, False,  True,  True,  True]])

In [93]:
arr[arr > .5]

array([0.76321887, 0.96842855, 0.94926278, 0.97456154, 0.93694308,
       0.58251287, 0.6674287 , 0.84622084, 0.84918105, 0.92705247,
       0.70841282])

In [94]:
arr[[1,2], [2]]

array([0.97456154, 0.25583818])

In [95]:
arr = np.random.rand(8, 5)

In [96]:
arr[1:8, [0,1,2]]

array([[0.61918031, 0.87394225, 0.70802798],
       [0.97234119, 0.04109977, 0.51181196],
       [0.94974209, 0.23466926, 0.80707858],
       [0.51561936, 0.30381498, 0.35259447],
       [0.46321336, 0.20728387, 0.22678734],
       [0.83655565, 0.46821719, 0.64324384],
       [0.32979151, 0.57534815, 0.92997747]])

In [101]:
a = np.array([[1,2],[3,4]])

In [102]:
b = np.array([[1,5],[3,5]])

In [104]:
m = a@b

In [105]:
m/0

C:\Users\win\AppData\Local\Temp/ipykernel_15920/3791875896.py:1: RuntimeWarning: divide by zero encountered in true_divide
  m/0


array([[inf, inf],
       [inf, inf]])