In [1]:
import pandas as pd


In [2]:
df = pd.read_csv("D:\\Ineuron\\DataSet\\train.csv", sep = ",")


In [3]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
df.dtypes


PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [5]:
df.index

RangeIndex(start=0, stop=891, step=1)

In [6]:
df.Age

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [7]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [8]:
df.Age.describe()

count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64

In [9]:
df.Age.mean()

29.69911764705882

In [10]:
type(df)

pandas.core.frame.DataFrame

In [11]:
import numpy as np
arr = np.array([1,2,3])
np.mean(arr)

2.0

In [12]:
l = list(df.Age)

In [13]:
for i in range(len(l)):
    if i % 2 == 0 :
        print(l[i])

22.0
26.0
35.0
54.0
27.0
4.0
20.0
14.0
2.0
31.0
35.0
15.0
8.0
nan
nan
40.0
nan
28.0
nan
18.0
40.0
nan
19.0
nan
nan
7.0
49.0
65.0
21.0
5.0
22.0
45.0
nan
29.0
17.0
32.0
21.0
32.0
nan
0.83
22.0
nan
17.0
16.0
23.0
29.0
46.0
59.0
71.0
34.0
28.0
21.0
37.0
21.0
38.0
47.0
22.0
17.0
70.5
24.0
21.0
32.5
54.0
nan
nan
33.0
47.0
25.0
19.0
16.0
nan
24.0
18.0
27.0
36.5
51.0
55.5
nan
16.0
nan
44.0
26.0
1.0
nan
nan
61.0
1.0
56.0
nan
30.0
nan
9.0
4.0
nan
40.0
32.0
19.0
44.0
nan
nan
28.0
34.0
18.0
32.0
16.0
24.0
22.0
nan
27.0
32.0
16.0
51.0
38.0
19.0
18.0
35.0
59.0
24.0
44.0
19.0
nan
29.0
30.0
25.0
37.0
nan
62.0
41.0
nan
35.0
nan
52.0
nan
16.0
58.0
nan
41.0
nan
45.0
7.0
65.0
16.0
nan
30.0
42.0
26.0
36.0
24.0
23.5
nan
nan
19.0
nan
nan
30.0
24.0
26.0
43.0
24.0
31.0
22.0
30.0
nan
61.0
31.0
nan
38.0
nan
29.0
45.0
2.0
28.0
36.0
40.0
3.0
23.0
15.0
nan
22.0
nan
40.0
45.0
nan
60.0
nan
25.0
19.0
3.0
22.0
20.0
42.0
32.0
nan
1.0
nan
36.0
28.0
24.0
31.0
23.0
39.0
21.0
20.0
51.0
21.0
nan
33.0
44.0
34.0
30.0
nan
29.0


In [14]:
df.Age[df.Age % 2 == 0]

0      22.0
1      38.0
2      26.0
6      54.0
7       2.0
       ... 
879    56.0
882    22.0
883    28.0
889    26.0
890    32.0
Name: Age, Length: 380, dtype: float64

In [15]:
arr+2

array([3, 4, 5])

In [16]:
arr1 = np.array([1,2,3])

In [17]:
arr*arr1

array([1, 4, 9])

In [18]:
np.multiply(arr, arr1)

array([1, 4, 9])

In [19]:
df.Age[df.Age.isnull() == True]
np.where(df.Age.isnull() == True)

(array([  5,  17,  19,  26,  28,  29,  31,  32,  36,  42,  45,  46,  47,
         48,  55,  64,  65,  76,  77,  82,  87,  95, 101, 107, 109, 121,
        126, 128, 140, 154, 158, 159, 166, 168, 176, 180, 181, 185, 186,
        196, 198, 201, 214, 223, 229, 235, 240, 241, 250, 256, 260, 264,
        270, 274, 277, 284, 295, 298, 300, 301, 303, 304, 306, 324, 330,
        334, 335, 347, 351, 354, 358, 359, 364, 367, 368, 375, 384, 388,
        409, 410, 411, 413, 415, 420, 425, 428, 431, 444, 451, 454, 457,
        459, 464, 466, 468, 470, 475, 481, 485, 490, 495, 497, 502, 507,
        511, 517, 522, 524, 527, 531, 533, 538, 547, 552, 557, 560, 563,
        564, 568, 573, 578, 584, 589, 593, 596, 598, 601, 602, 611, 612,
        613, 629, 633, 639, 643, 648, 650, 653, 656, 667, 669, 674, 680,
        692, 697, 709, 711, 718, 727, 732, 738, 739, 740, 760, 766, 768,
        773, 776, 778, 783, 790, 792, 793, 815, 825, 826, 828, 832, 837,
        839, 846, 849, 859, 863, 868, 878, 888], dt

In [20]:
a = df.Fare.max()

In [21]:
maxIndex = np.where(df.Fare ==a)
type(df.iloc[maxIndex])

pandas.core.frame.DataFrame

In [22]:
df.iloc[maxIndex].Name

258                      Ward, Miss. Anna
679    Cardeza, Mr. Thomas Drake Martinez
737                Lesurer, Mr. Gustave J
Name: Name, dtype: object

In [23]:
max(df.Fare)

512.3292

In [24]:
df[df.Age == 24].Name

89                                Celotti, Mr. Francesco
118                             Baxter, Mr. Quigg Edmond
127                            Madsen, Mr. Fridtjof Arne
139                                   Giglio, Mr. Victor
142    Hakkarainen, Mrs. Pekka Pietari (Elin Matilda ...
199               Yrois, Miss. Henriette ("Mrs Harbeck")
210                                       Ali, Mr. Ahmed
234                    Leyson, Mr. Robert William Norman
247                      Hamalainen, Mrs. William (Anna)
293                                  Haas, Miss. Aloisia
294                                     Mineff, Mr. Ivan
310                       Hays, Miss. Margaret Bechstein
316                  Kantor, Mrs. Sinai (Miriam Sternin)
341                       Fortune, Miss. Alice Elizabeth
345                        Brown, Miss. Amelia "Mildred"
369                        Aubart, Mme. Leontine Pauline
394    Sandstrom, Mrs. Hjalmar (Agnes Charlotta Bengt...
437                Richards, Mr

In [25]:
df[df.Cabin.isnull() == True][['Age','Cabin']]

Age Cabin
0    22.0   NaN
2    26.0   NaN
4    35.0   NaN
5     NaN   NaN
7     2.0   NaN
..    ...   ...
884  25.0   NaN
885  39.0   NaN
886  27.0   NaN
888   NaN   NaN
890  32.0   NaN

[687 rows x 2 columns]

In [26]:
arr1= np.array([1,2])

In [27]:
arr + 2

array([3, 4, 5])

In [28]:
df.iloc[0:2,0:2]


PassengerId  Survived
0            1         0
1            2         1

In [29]:
np.random.seed(23)
df1 = pd.DataFrame(np.random.randn(4,5), index = ('x','y','z','u'), columns = ('a','b','c','d','e'))

In [30]:
df1

a         b         c         d         e
x  0.666988  0.025813 -0.777619  0.948634  0.701672
y -1.051082 -0.367548 -1.137460 -1.322148  1.772258
z -0.347459  0.670140  0.322272  0.060343 -1.043450
u -1.009942  0.441736  1.128877 -1.838068 -0.938769

In [31]:
df1.index

Index(['x', 'y', 'z', 'u'], dtype='object')

In [32]:
for i in df1.columns:
    if df1.loc[i] < 0
        print(df1.i[df1.i < 0])


SyntaxError: invalid syntax (Temp/ipykernel_5012/2200925777.py, line 2)

In [ ]:
print(df1.a[df1['a'] < 0])

In [ ]:
df1.columns

In [ ]:
np.where(df1 < 0)

In [ ]:
for i in df1.columns:
    for j in df1.index:
        if df1.loc[j,i]< 0:
            print(j,i)

In [ ]:
df1.iloc[0,0]


In [33]:
df1


a         b         c         d         e
x  0.666988  0.025813 -0.777619  0.948634  0.701672
y -1.051082 -0.367548 -1.137460 -1.322148  1.772258
z -0.347459  0.670140  0.322272  0.060343 -1.043450
u -1.009942  0.441736  1.128877 -1.838068 -0.938769

In [35]:
LeftArr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [39]:
for i in 


AttributeError: 'numpy.ndarray' object has no attribute 'row'

In [37]:
LeftArr[LeftArr > 5]

array([6, 7, 8, 9])

In [49]:
for i in range(len(LeftArr)):
    for j in range(len(LeftArr[i])) :
        if LeftArr[j, i] > 5:
            print(LeftArr[j, i])

7
8
6
9


In [45]:
LeftArr[1,2]

6

In [48]:
2**2.5

5.656854249492381

In [52]:
for i in LeftArr:
    if i[i>5]:
        print(i)


[4 5 6]


C:\Users\win\AppData\Local\Temp/ipykernel_5012/3011847579.py:2: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if i[i>5]:


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [53]:
for i in LeftArr:
    print(type(i))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [55]:
print(arr[arr <2])

[1]


In [1]:
pwd


'C:\\Users\\win'

In [2]:
ls

 Volume in drive C has no label.
 Volume Serial Number is 0CEE-C01D

 Directory of C:\Users\win

02-01-2022  15:24    <DIR>          .
02-01-2022  15:24    <DIR>          ..
03-12-2021  01:42    <DIR>          .conda
28-11-2021  12:21                25 .condarc
28-11-2021  12:21    <DIR>          .continuum
04-05-2020  22:54    <DIR>          .idlerc
01-01-2022  17:04    <DIR>          .ipynb_checkpoints
02-12-2021  22:41    <DIR>          .ipython
04-12-2021  10:12    <DIR>          .jupyter
25-12-2021  17:13    <DIR>          .matplotlib
07-12-2021  00:42                20 .python_history
05-10-2020  03:27    <DIR>          3D Objects
28-11-2021  12:16    <DIR>          anaconda3
26-12-2021  19:42            14,257 Condition and For loop.ipynb
05-10-2020  03:27    <DIR>          Contacts
14-03-2021  17:31    <DIR>          Desktop
28-11-2021  12:16    <DIR>          Documents
28-12-2021  23:46    <DIR>          Downloads
05-10-2020  03:27    <DIR>          Favorites
27-12-2021  01:00

In [9]:
d1 = {"UserId": 12, "Age": 24}
d2 = {"UserCode": 25, "Age": 20}
list1 = []
list1.append(d1)
list1.append(d2)

In [10]:
import pandas as pd

In [11]:
pd.DataFrame(list1)

UserId  Age  UserCode
0    12.0   24       NaN
1     NaN   20      25.0

In [8]:
list1

[{'UserId': 12, 'Age': 24}, {'UserId': 25, 'Age': 20}]